<div class="version-notice">
    <p><strong><?= $block->escapeHtml(__('Magento version'))?>:</strong> <?= $block->escapeHtml($this->getMagentoVersion());?></p>
    <p><strong><?= $block->escapeHtml(__('Magento Econnect version'))?>:</strong>  <?= $block->escapeHtml($this->getEconnectVersion());?></p>
    <p><strong><?= $block->escapeHtml(__('Magento Econnect SX.e version'))?>:</strong>  <?= $block->escapeHtml($this->getSXEversion());?></p>
    <p><strong><?= $block->escapeHtml(__('ION version'))?>:</strong>  <?= $block->escapeHtml($this->getIONVersion());?></p>
</div>
